### ISSUE TITLE
model... unconverged

### ISSUE THREAD

**Issue by kumarsaurabh20** [schatzlab/genomescope#12]
I am trying to generate k-mer distribution using a histo file but I don't think the resulting distribution is not making sense. Also, the model is unconverged in round 0 and round 2.  Does it mean the model doesn't fit the data? Furthermore, the heterozygosity is coming 2.7%. With this rate, I expect a bimodal graph?  
[beast_19_2.histo.txt](https://github.com/schatzlab/genomescope/files/1952141/beast_19_2.histo.txt)

Any suggestions?

**Comment by mschatz** [comment]
Thanks for your interest! Unfortunately, it looks like the overall coverage
is too low for it to make a confident inference. Looking manually, there is
a hint of a coverage peak at 6x coverage but Im nervous to use that since
there can be a lot of coincidental sequencing errors at that level of
coverage and heterozygosity is particularly challenging to resolve. If you
are looking to do de novo assembly, you will definitely want to
include/generate additional data, although if you have a reference
available, you might be able to call variants.

Good luck!

Mike

**Comment by kumarsaurabh20** [comment]
Many thanks Mike. Yes, the data coverage is really low and that answers all the issues.
