### ISSUE TITLE
expectations for pooled samples

### ISSUE THREAD

**Issue by rsbrennan** [schatzlab/genomescope#124]
I'm working with a copepod that is small. To generate enough tissue for sequencing, we took a semi-inbred lab population and did an additional three generations of sib-crosses, then grew these up to a few thousand individuals for sequencing. What this means is that we likely have four haplotypes present in the data. 

For genomescope analysis, I'm wondering if it makes sense to run these are diploid or tetraploid? As you might expect, if I specify tetraploid, the genome size estimate is halved from the diploid estimate. The model fit might also be a bit better. 

These are HiFi data.

Ploidy 2: http://genomescope.org/genomescope2.0/analysis.php?code=kG1UTtXPPdcBcAb3m7Ox
Ploidy 4: http://genomescope.org/genomescope2.0/analysis.php?code=6NE9ua0kzC2lNsflRi0m

My questions:
1. Are either of these genome size estimates reliable? I'm leaning towards the tetraploid estimate as being more reliable, but am not sure this is reasonable.
2. Would the presence of multiple haplotypes from pooling individuals explain the lack of second obvious peak in the plot?

Thanks for any help/thoughts,
Reid

**Comment by mschatz** [comment]
In theory the tetraploid model would be better here, although I don't love
the fit for either model. Based on these results, I would put the (haploid)
genome size at around 700Mbp or 1Gbp, but I cant narrow it down any more
than this. In generally mixing haplotypes will inflate the genome size
estimate since all those variants will add up as additional sequence.
Speaking of which, the variability between the haplotypes also (partially)
explains the shape of the distribution. This suggests that most variation
is private to one of the 4 haplotypes, but there is some that is shared in
2, 3 or all 4. Sorry I cant be of more help - this would require a
different statistical model (and probably additional data) to pin down more
precisely

Good luck!
Mike

**Comment by rsbrennan** [comment]
Thanks Mike. This is quite helpful. Really appreciate you sharing your thoughts!
