### ISSUE TITLE
Ploidy determination

### ISSUE THREAD

**Issue by Samyuktha9624** [schatzlab/genomescope#130]
Hello,

  The samples I am working on are diploid and this is a known fact. However, when I am analysing whole genome short read data the ploidy level on Genomescope result is haploid. What are the possible causes? 

I am unsure how to go about this, any help is greatly appreciated. Thanks!

**Comment by mschatz** [comment]
Im guessing you mean that there is only a single peak on the kmer
distribution. This can occur within diploid samples with either very low or
very high rates of heterozygosity At very low rates (~0.1% or less,
especially inbred samples) the secondary peak for heterozygous kmers will
be so small that it will be obscured by sequencing errors and any other
noise in the data. On the other hand, if there is a very high rate of
heterozygosity (>2%) the peak of kmers that are heterozygous is so large
that it completely overwhelms the distribution to obscure the peak from
homozygous kmers. Note the heterozygous peak grows quite quickly because a
single heterozygous SNV will contribute 2*k heterozygous kmers, e.g. a
single SNV creates 42 heterozygous k-mers using k=21

Otherwise, you may get unusual peaks if you have very low coverage (the
individual peaks merge together), high rates of errors (especially
uncorrected ONT reads that "hide" heterozygous kmers), or other
artifacts/contaminates in the data

Hope this helps!
Mike

**Comment by Samyuktha9624** [comment]
Thank you so much!
