### ISSUE TITLE
Is command line for ploidy different?

### ISSUE THREAD

**Issue by gunjanpandey** [schatzlab/genomescope#134]
is there a flag that needs adding for suspected polypolidy while running geomescope2? Or the software automatically detects the polidy with default command?

` "Rscript ${genomescope} -i meryl.hist -k 19 -o out_genomescpe"`

**Comment by mschatz** [comment]
Note the original genomescope only supports diploid, but genomescope2
supports other ploidy values. For genomescope2 by default it will assume
ploidy=2, otherwise for other ploidy values use the -p parameter. You can
also run genomescope2 via the web: http://genomescope.org/genomescope2.0/

Good luck!
Mike

**Comment by gunjanpandey** [comment]
Thanks Mike. 
So, I need to add `-p 4` here for tetrapolidy?

`Rscript ${genomescope} -i meryl.hist -k 19 -o out_genomescpe -p 4`

**Comment by mschatz** [comment]
Yes!

**Comment by gunjanpandey** [comment]
Thanks again. 
it is sorted.
