### ISSUE TITLE
Why didnt the model converge? continued

### ISSUE THREAD

**Issue by peterthorpe5** [schatzlab/genomescope#14]
Hi Genomescope,

Thanks for making the tool, this sounds like a great tool!! :+1:  . I want to use it as I really want to know the predicted genome size and heterozygosity of my beast! I tried reducing the kmers from 31 down to 15 to try and increase the coverage:

$ jellyfish count -C -t 16 -m 15 -C -s 200000000 -o pe_data.jf15 both.fq
$ jellyfish histo -t 16 -o pe_data.jf15_0.jellyfish.histo pe_data.jf15_0

But the data (all of the kmer histogram, k=15 attached) always fails to converge using the online web server.  http://genomescope.org/analysis.php?code=KhsSDR8CcZ8i6umW160j 

Is there anything that can be done to try and fix/ help this? The mean coverage of the reads when mapping back to the Illumina assembly is 110X.

A little bit of background:
We believe this sample (nematode) to have high amounts of heterozygosity. I have performed a ploidy analysis using nQuire which statistically thinks it could be tetraploid, but the histogram does not agree (ploidy analysis could be affected due to the sample being a population). Literature has always said it is diploid. The sequencing material was thousands of nematodes, as they are very small). The Illumina assembled genome size = 120Mbp (SPAdes). PacBio data = 320Mbp (Canu default, running again trying to force haplotypes together). 

[pe_data.jf15_0.jellyfish.histo.txt](https://github.com/schatzlab/genomescope/files/2023100/pe_data.jf15_0.jellyfish.histo.txt)

**Comment by mschatz** [comment]
Hi Peter,

Thanks for your interest. Looking at the histogram and some of the
internals of the code, the model isnt converging because there isnt a clear
peak in the data. For example, compare your histogram to the histogram from
Arabidopsis or the other example datasets that have nice peaks:
http://qb.cshl.edu/genomescope/analysis.php?code=example6

This generally means you need additional coverage to resolve the peaks
(even with polyploids). It also confuses things that there are thousands of
nematodes, since then it will get a mixed signal from all of the
individuals. If you do additional sequencing, you might want to consider
one of the ultra-low input DNA kits that I think only requires a few
nanograms of DNA so might be practical to sequence a single individual.

Good luck

Mike
