### ISSUE TITLE
different results at different coverage

### ISSUE THREAD

**Issue by AlcaArctica** [schatzlab/genomescope#146]
I obtained hifi data on a diploid animal species. The lab performed two PacBio runs with the same library, as after the first one we discovered we had not yet obtained enough data. So I performed Genomescope2 on both runs and on the data of both runs combined. Interestingly I get very different results depending on which input I use:

![image](https://github.com/user-attachments/assets/d62621bd-c274-4908-8ebc-20f2a7a231d8)

So from this I can see, that with too low coverage Genomescope produces very different results than when I provide it with more data. Especially interesting is that it predicts a much higher het rate (2.5 % vs 0.5 %) and smaller genome sizes (1000 Mbp vs 2000 Mbp) and differences in the percentage of repeated regions (60 vs 80 %). 

Now surely, the result of the combined data is the best. But this makes me wonder, would more data be even better? Would the Genomescope2 results change further? I do not know what is the true genome size, so it is hard to predict what coverage I should need. Assuming the lates Genomescope2 result is true and we are indeed dealing with a genome of 2000 Mbp, I have still not reached 15 x coverage for each haplotig. So would it be recommended to request still more hifi sequencing data?

**Comment by mschatz** [comment]
I would not trust the results from the individual runs as it has too low of
coverage to make a reliable prediction (the model can get confused between
homozygous and heterozygous peaks at very low coverage which is why the
combined data is predicted to be twice the genome size as the individual
runs). The results from the combined data look fairly reliable for
genomescope so I would not expect these estimates to change much with more
data. On the other hand, even with the data combined, the major peak is at
about 15x coverage, which is a little low for a de novo assembly. If you
have resources for it, another run (or two) would be helpful (Id recommend
25-30x for de novo assembly, and some assemblers like verkko are optimized
for 50x). Fortunately, from the shape of the peak, it doesnt look like your
sample has extreme levels of heterozygosity, so I would expect a good
assembly, assuming your reads are ~15kbp or so. Have you tried assembling?
I would recommend hifiasm for this. We have a push button pipeline that you
can try (for free!) through galaxy:
https://www.nature.com/articles/s41587-023-02100-3

Good luck!
Mike

**Comment by AlcaArctica** [comment]
Hi Mike, thank you so much for this very helpful reply. I will look into getting more data for this species. We have done an initial assembly with hifiasm plus HiC data and it is acceptable, but not the best.
