### ISSUE TITLE
underestimation of genome size

### ISSUE THREAD

**Issue by Anh-Thu-Weber** [schatzlab/genomescope#15]
Hi,

Thank you for providing this handy tool!
I am interested in estimating the genome size of a fish using kmer analysis. 

I did it "by hand" using this tutorial:
https://bioinformatics.uconn.edu/genome-size-estimation-tutorial/

and I used your web browser, but I got quite different genome size estimates:

by hand:
total kmer in the distribution: 17274199130
highest coverage: 18
genome size estimate: 959677729 (~960Mb) [the first three bins were removed for the calculation]

web browser (kmer length 25; read length 150; no max kmer cov filtering)
genome size estimate: 842099351 (~842Mb)

The assembly size of a closely related species is 957Mb so I guess the calculation "by hand" is more accurate?  Do you know the reason of this discrepancy?

I attached the hist file from jelltfish & the genomescope outfiles 

Thank you in advance,

Alexandra

![genomescope_profile1_kbc7](https://user-images.githubusercontent.com/34683973/42926351-74e6f6dc-8b74-11e8-9212-99998d9d10bc.png)
![genomescope_profile2_kbc7](https://user-images.githubusercontent.com/34683973/42926352-7523ff14-8b74-11e8-9a0f-269fa3e8c971.png)
[KBC7_k25.histo.txt](https://github.com/schatzlab/genomescope/files/2208640/KBC7_k25.histo.txt)

**Comment by mschatz** [comment]
Hi Alexandra,

The "by hand" method is similar to what GenomeScope uses, although GenomeScope adds a couple additional step to get a more accurate result. First, in your data there are many kmers that only occur once or twice, and these are almost always just sequencing errors. Thats why your data has a tall spike at the far left that the model in black doesnt capture. It is generally a good idea to exclude these since they will artificially inflate your genome size estimate. In addition, the "top" of the peak is at 18, but your data are over-dispersed from a Poisson distribution so the real mean is closer to 20 so your estimate will lead to a larger genome size. Finally I see that your histogram ends right at 10,000x coverage, but there can be real kmers in the genome that have even higher coverage, so the true genome size might be a bit larger than GenomeScope reports. You can investigate this by increasing the limit on jellyfish to around 1,000,000 although then you need to be really careful about an contaminates in the data. At minimum Id recommend excluding any kmers that map to phiX. Once you have these kmers added, Id recommend you report the GenomeSize estimate since it has been validated in many samples.

Good luck!

Mike

**Comment by Anh-Thu-Weber** [comment]
Hi Mike,

Thank you very much for your quick and detailed answer!

Alexandra
