### ISSUE TITLE
model... unconverged fail

### ISSUE THREAD

**Issue by dzaccook** [schatzlab/genomescope#17]
Hi,
I want to generate k-mer distribution using a the histo file, but the model is unconverged.
starting
round 0 trimming to 15 trying 4peak model... unconverged
round 1 trimming to 20 trying 4peak model... unconverged
round 2 trimming to 25 trying 4peak model... unconverged
round 3 trimming to 30 trying 4peak model... unconverged
fail
But I can see two peaks in the data.
Can you give me some help?
Thanks!
[19mer.histo.txt](https://github.com/schatzlab/genomescope/files/2655561/19mer.histo.txt)

**Comment by mschatz** [comment]
Your kmer profile is rather unusual. There are no noticeable peaks between
10x to 100x coverage, although there are some far out at around 200x to
500x coverage. GenomeScope is getting confused because those peaks are so
far out, which also implies the amount of sequencing error is very
high.  Is it plausible that you have that much coverage? If so you might
need to downsample some, although the high error rate will be difficult to
work with. Was there anything else unusual about the sequencing? Maybe you
are pooling multiple samples together?

Good luck!

MIke

**Comment by dzaccook** [comment]
Thank you for your reply.
It is a plant sample, so it should not be pooling multiple samples, the sequencing coverage is about 100x according to FCW result. Is it affected by ploidy?

**Comment by mschatz** [comment]
It could be affected by ploidy. The published version of GenomeScope only
deals with diploid samples, although we have a new unpublished version that
can work with hexaploids or lower ploidy. Do you know the ploidy of your
sample?

Cheers

Mike

**Comment by dzaccook** [comment]
Commonly, it is diploid, but I need to further confirmed. By the way, can you release the new version to me for testing?
Thank you!

**Comment by dzaccook** [comment]
I will confirm the ploidy using chromosome preparation technique.
