### ISSUE TITLE
Difference in genome size estimation between GS/GS2

### ISSUE THREAD

**Issue by conchoecia** [schatzlab/genomescope#28]
I am working with a very heterozygous, **diploid** species whose genome is around 150-200Mbp. I have a lot of shotgun coverage for this species, and the k-mer spectra are nicely separated. Yes, the heterozygous peak really is that big, and yes - the "1X" coverage peak is around 96.

![plot](https://user-images.githubusercontent.com/3123273/68155226-1c369c00-fefe-11e9-98a3-e2778602bba2.png)

However, when I run the same spectrum on GS1 vs GS2, the genome size estimates are very different. I have made a plot using two individuals (Labelled Bf201606 and Bf201311), and compared the results of the minimum genome size from GS1 and GS2. As you can see, the genome size estimate for GS2 is much larger than GS.

![genome_size_prediction_white_edited](https://user-images.githubusercontent.com/3123273/68155333-5b64ed00-fefe-11e9-9eba-ced376663c33.jpg)

Do you have any idea why the estimates are so different? Thank you for writing and maintaining GS/GS2!!!

**Comment by mschatz** [comment]
Thanks for your interest! We generally recommend GenomeScope 2.0 for all
users since it is more accurate and more robust to different species. Im
guessing the difference in genome size is because of the max kmer coverage
- in GenomeScope 1.0 we recommended 1000 to exclude organelle sequences and
other artifacts, but for GenomeScope 2.0 we find it is more accurate to
include the high frequency kmers

Good luck!

Mike

**Comment by conchoecia** [comment]
Great, Thanks!
