### ISSUE TITLE
Only 1 Peak in genomescope plot

### ISSUE THREAD

**Issue by jhcaddisfly** [schatzlab/genomescope#47]
Hi,

I used Genomescope 2 on a many genomes and it workswell for most of my data.
I am working on diploid species and in most of the cases I get two peaks in the plot.
However, for a few I only get one peak. For example here:
What does this actually mean? Shouldn't there be two? Might this indicate that the species is not diploid?
Also, the assembly length based on this data is 1,233,588,871 bp. 
What could explain the difference? Might the smaller estimate may be due to the additional parameter introduced in GenomeScope, set to exclude extremely high-frequency kmers as these likely represent organelle sequences or other contaminants that can inflate the genome size?
However, I used the following parameters:
k-mers were counted with JELLYFISH v2.2.10  jellyfish count -C -s 25556999998 -F 3 and a k-mer length of 21 (-m 21). A histogram of k-mer frequencies was produced with jellyfish histo. GenomeScope 2.0 was run with the following parameters:
Kmer length = 21, Max kmer coverage = 10000.

Thanks for any input on this question!

![grafik](https://user-images.githubusercontent.com/55246900/99958630-022a5e80-2d8a-11eb-9827-be94292dce21.png)

**Comment by mschatz** [comment]
This looks like a data quality issue - the algorithm sees that there is a pretty high rate of heterozygosity (0.488%) but the second peak is obscured because of the quality. Notice how for the main peak (with the mode at 38/39x) there is a "shoulder" of additional kmers at around 19x that are due to the heterozygosity in the data. This is obscured by the error kmers with coverage between 1x and ~20x, plus the broad peaks suggests a high rate of PCR duplicates. Have you tried running FastQC? But even though the peaks are not sharp, I would expect the estimates on genome size, uniqueness, and overall heterozygosity to be reliable

Good luck

Mike
