### ISSUE TITLE
Unable to distinguish heterozygous peak

### ISSUE THREAD

**Issue by cdmmoeller** [schatzlab/genomescope#55]
Hi,

I recently ran the Genomescope2 webserver on a kmer spectrum generated from ~770Gb of cleaned PE Illumina data. The genome has previously been estimated to be of size 6-7Gb and diploid. 

My problem seems to be that the tail of the peak of low-frequency kmers arising from sequencing errors collides with the peak of heterozygous kmers, making the latter indistinguishable.

My first thought was this is due to low-quality data. However, this data is quality-filtered (SLIDINGWINDWINDOW:4:22 in trimmomatic), and filtering it even more stringently did not help the problem. I have also checked for contaminants with fastq_screen and found none. 

1. I would be grateful if you have any idea about what could cause this phenomenon and if there is anything that can be done to have a spectrum with a clearer heterozygous peak.

2. How reliable is the genome size estimate by Genomescope2? The model seems to fit the homozygous peak well enough, but I am not sure since the overall fit isn't that great.

Thanking you in advance,
Christian

![23mer_linear](https://user-images.githubusercontent.com/47928057/115180295-3bd07d00-a110-11eb-8905-c5259275cf37.png)

![genomescope_model](https://user-images.githubusercontent.com/47928057/115180630-0b3d1300-a111-11eb-978a-cf420dcc30e0.PNG)

**Comment by mschatz** [comment]
Hi Christian

Thanks for your interest. Im afraid as you say it looks like the errors
from sequencing errors are colliding with the heterozygous kmer peak. I
would normally recommend trimming to remove those erroneous kmers but
sounds like you have already done pretty extensive filtering so there is
not too much that can be done short of collecting new data. I agree the fit
is not that great, most likely because the model is trying to fit within
the error peaks that are bleeding into the heterozygous peak.

Another potential reason why the estimated genome size is smaller than you
expect is because of filtering of high frequency kmers. By default
jellyfish will limit the max kmer coverage to 10,000. Can you try raising
this to 1,000,000 (or so). This can introduce some other issues if there is
any contamination but is often necessary for these very large genomes

Good luck!

Mike

**Comment by cdmmoeller** [comment]
Hi Mike,

Thanks for your reply.

Actually, the previous result is from a histogram of 23mers counting up to a coverage of 10,000,000 (`-cs 10000000` in KMC3). I should have included the log-scale plot.

The following plots are from a histogram counting up to 1,000,000 coverage (max kmer coverage setting in Genomescope2). The estimated size has thus dropped slightly (5.78G -> 5.56G).

Would it make sense to increase the kmer size to say, 27?

![23mer_max1e6](https://user-images.githubusercontent.com/47928057/115186929-7856a580-a11d-11eb-8a58-c7966768d769.PNG)

**Comment by mschatz** [comment]
Thanks. On the log-log plot there are some kmers with over 1 million fold
coverage so you may need to boost this even higher (although will probably
have marginal impact on genome size). It probably wont help much to
increase the kmer size to 27 since it is so similar. Sadly I think you will
need newer / lower error data to move much beyond this

Good luck

Mike

**Comment by cdmmoeller** [comment]
I see, thank you for your help.
