### ISSUE TITLE
Please provide download of results from website

### ISSUE THREAD

**Issue by mmokrejs** [schatzlab/genomescope#6]
Hi,
  I lack an option to download my results from http://qb.cshl.edu/genomescope website. I also tried from firex "Save as" and `wget --mirror -l2` but they both failed.

  Ideally if one could group results and get animated GIF figures (I ran k-mer counting at various k-mer sizes).

Thank you

**Comment by mschatz** [comment]
Can you give the full URL you are trying? You should be able to save the plots by using the "Save As" menu option in your browser. For example, here is the full URL for a recent run:
http://qb.cshl.edu/genomescope/analysis.php?code=UyWTAXyzTJK6mHZPnqxh

And the individual plots can be accessed like this:
http://qb.cshl.edu/genomescope/user_data/UyWTAXyzTJK6mHZPnqxh/plot.png
http://qb.cshl.edu/genomescope/user_data/UyWTAXyzTJK6mHZPnqxh/plot.log.png

I would not use wget since the computation runs on the fly and can take 30 seconds to 1 minute to compute so wget might time out.

Hope this helps

Mike

**Comment by mschatz** [comment]
As it is now, we expect users to work interactively in the browser so they
can just download the plots there. If you want to run it on the command
line, it is really just one script that you need (the repo has the testing
data so we can do regression tests):
https://github.com/schatzlab/genomescope/blob/master/genomescope.R

The current interface doesnt support uploading multiple kmer histograms at
once so it is much more complicated than your code snippet, but glad to see
you can generate it on your own. I think it is also a research question to
determine when this helpful -- in our tests we try to use the shortest kmer
length that is expected to be unique in the genome (usually 21mers) since
longer kmers are more likely to overlap multiple errors and/or heterozygous
sites which obscures their true frequency. The model tries to accommodate
for this by assuming a steady rate of errors & heterozygosity in those
regions but it helps to have more information. We are in the process of
rebuilding the whole process to support more complicated genomes so will
keep this in mind.

Cheers

Mike

**Comment by mschatz** [comment]
Also, "Save Image As" works for me for your results in Chrome, Firefox, and Safari:
 http://qb.cshl.edu/genomescope/analysis.php?code=UyWTAXyzTJK6mHZPnqxh 

Must be an issue on your side.

Good luck!

Mike

**Comment by mmokrejs** [comment]
"Save Image As" of course works, but "Save Page As" does not.

**Comment by mschatz** [comment]
Please try again, works for me (left: CSHL server, right: local machine)

Good luck!

Mike

![screen shot 2018-02-16 at 2 12 28 pm](https://user-images.githubusercontent.com/196083/36324780-8e0d67a0-1323-11e8-8e25-62d88e32fa40.png)
