### ISSUE TITLE
Improving figure legends

### ISSUE THREAD

**Issue by mmokrejs** [schatzlab/genomescope#7]
Hi,
  thank you for a nice tool. I find the description of figures incomplete. I am newbie in this type of genome analysis but I think the Y-axis should probably read "Observed k-mer frequency". There is no description what is `kcov`, `err`, `uniq`, `het`, `dup`, `len`. The vertical dashed lines (supposedly the identified k-mer peaks) should be labeled within the figure with X and Y values. The X-axis is maybe `Absolute coverage` (to give an idea how many sites/loci are haploid, diploid, tetraploid)?
  The figures should retain the information what `Read length` user provided during analysis.
  Finally, the minimum where `Error` and `Full model` curves cross each other should be labeled as well. That should be my target minimum requirement for a contig coverage for an upcoming assembly, right? Then please depict the X and Y- value of this valley in the figure, and include them in a table below.

**Comment by mschatz** [comment]
There isnt space on the plot to provide a detailed explanation of every characteristic, but I encourage you to review the published paper where we explain the terms:
https://academic.oup.com/bioinformatics/article-abstract/33/14/2202/3089939?redirectedFrom=fulltext

The supplement has a detailed explanation of the statistical model behind the analysis.

Briefly:

len: inferred total genome length
uniq: percent of the genome that is unique (not repetitive)
het: overall rate of heterozygosity
kcov: mean kmer coverage for heterozygous bases. note the top of the peak will not intersect the kcov line because of the over dispersion in real data
err: error rate of the reads
dup: average rate of read duplications

Good luck!

Mike

**Comment by mmokrejs** [comment]
Hi Mike,
  thank you for your kind answer. There is enough space at least on the website to include the above explanations.

  And for sure the Y-axis has enough space to be clearer. Our students would not pass if they showed up such figures in their presentations. Again, the Y-axis reads `Frequency`, `0.0e+00`, `1.0e+07`, `2.0e+07`.

  I think I raised quite a few good suggestions in the original comment too but it makes no sense to repeat myself. Good luck to you too!

Martin
