### ISSUE TITLE
failed to converge

### ISSUE THREAD

**Issue by plnspineda** [schatzlab/genomescope#88]
Hi! I would like to ask how to possible trouble shoot this? I believe I have good coverage for my 2.9Gb diploid genome. The histo file are from the 150bp pe short reads. Both histo from jellyfish and meryl are giving me the same failed to converge problem.

I believe the coverage is not the problem since the first graph is showing peak at 40? Tried it as well with kmer max coverage at 10000, 1000000, and 9000000 and I keep getting the same result.

This is from jellyfish histo
![2022-11-10_19-56_sp_buf_jf](https://user-images.githubusercontent.com/92421984/201052819-f41d334e-5061-4e5a-8bf2-561f2dd67488.png)

and this is from meryl histo
![2022-11-10_19-56_sp_buf_meryl](https://user-images.githubusercontent.com/92421984/201053649-cb99c4bb-6bd6-464a-bb04-1e0358d5f023.png)

The graphs are made from the website.
I'd appreciate your help. Thank you!

**Comment by tbenavi1** [comment]
Can you please attach the histogram file so I can troubleshoot. Thanks.

**Comment by plnspineda** [comment]
Thank you very much!

[sp_reads_.zip](https://github.com/schatzlab/genomescope/files/9980261/sp_reads_.zip)

**Comment by tbenavi1** [comment]
Hello, we recommend using version 2 of genomescope from www.genomescope.org/genomescope2.0. I tested your data and the updated model converges correctly. I would use the meryl histogram, since the jellyfish histogram you provided truncates at 10,000. (Alternatively, you can tell jellyfish to increase the max coverage). Let me know if you have any further issues.

**Comment by plnspineda** [comment]
Thank you very, didn't notice I am using the old version of the website. Got it resolved now.
